server:
  port: 8886
  tomcat:
    max-threads: 300
    min-spare-threads: 0
    max-connections: 200
    uri-encoding: UTF-8
logging:
  pattern:
    console: "%d - %msg%n"
spring:
  application:
    name: user
  jpa:
    show-sql: true
  shardingsphere:
    datasource:
      names: master,slave0
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://182.92.190.168:3306/user_core?useSSL=false&useUnicode=true&characterEncoding=utf8
        username: ops
        password: ops
      slave0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://59.110.172.84:3306/user_core?useSSL=false&useUnicode=true&characterEncoding=utf8
        username: opss
        password: opss
    sharding:
      tables:
        user:
          key-generator:
            type: SNOWFLAKE
            column: user_id
          actual-data-nodes: ds0.user_$->{0..9}
          table-strategy:
            inline:
              sharding-column: user_id
              algorithm-expression: user_$->{user_id % 10}
      binding-tables: user
      master-slave-rules:
        ds0:
          master-data-source-name: master
          slave-data-source-names: slave0
    props:
      sql:
        show: true
  cache:
    type: redis
    redis:
      key-prefix: cache
      cache-null-values: true
  aop:
    auto: true
  rabbitmq:
    host: localhost
    username: fanhehe
    password: 13889441200
    virtual-host: /fanhehe
    port: 5672
  redis:
    cluster:
      nodes: 127.0.0.1:6389,127.0.0.1:6390,127.0.0.1:6391,127.0.0.1:6392,127.0.0.1:6393,127.0.0.1:6394
      max-redirects: 3
    port: 6389
    host: 127.0.0.1
    database: 0
    password:
feign:
  hystrix:
    enabled: true
  okhttp:
    enabled: true
  httpclient:
    enabled: false
  compression:
    request:
      enabled: true
    response:
      enabled: true
user:
  ribbon:
    ConnectTimeout: 500 #请求连接超时时间
    ReadTimeout: 1000 #请求处理的超时时间
    OkToRetryOnAllOperations: true #对所有请求都进行重试
    MaxAutoRetriesNextServer: 2 #切换实例的重试次数
    MaxAutoRetries: 1 #对当前实例的重试次数
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #随机
