server:
  port: 18080
  tomcat:
    max-connections: 200
    max-threads: 300
    min-spare-threads: 0
    uri-encoding: UTF-8
logging:
  pattern:
    console: "%d - %msg%n"
  level:
    com.cnooc.wordimg.LoggerTest2: debug
spring:
  jpa:
    show-sql: true
  application:
    name: home
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/user?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
eureka:
  #eureka实例定义
  instance:
    #eureka实例主机名称
    hostname: localhost
    #表示eureka client发送心跳给server端的频率。如果在leaseExpirationDurationInSeconds后，server端没有收到client的心跳，
    #则将摘除该instance。
    #除此之外，如果该instance实现了HealthCheckCallback，并决定让自己unavailable的话，则该instance也不会接收到流量。
    lease-renewal-interval-in-seconds: 5
  #客户端进行Eureka注册的配置
  client:
    #关闭eureka的客户端行为:注册服务
    registerWithEureka: true
    #关闭eureka的客户端行为:订阅服务
    fetchRegistry: true
    serviceUrl:
      #eureka注册中心地址
      defaultZone: http://localhost:9999/eureka/
feign:
  hystrix:
    enabled: true
  okhttp:
    enabled: true
  httpclient:
    follow-redirects: true
    connection-timeout: 2000
    disable-ssl-validation: true