server:
  port: 9999
eureka:
  #eureka实例定义
  instance:
    #eureka实例主机名称
    hostname: localhost
    #表示eureka client发送心跳给server端的频率。如果在leaseExpirationDurationInSeconds后，server端没有收到client的心跳，
    #则将摘除该instance。
    #除此之外，如果该instance实现了HealthCheckCallback，并决定让自己unavailable的话，则该instance也不会接收到流量。
    lease-renewal-interval-in-seconds: 5
  #客户端进行Eureka注册的配置
  client:
    #关闭eureka的客户端行为:注册服务
    registerWithEureka: false
    #关闭eureka的客户端行为:订阅服务
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
  server:
    # 关闭自我保护机制，防止失效的服务也被一直访问 (Spring Cloud默认该配置是 true)
    enable-self-preservation: false
    # 每隔10s扫描服务列表，该配置可以修改检查失效服务的时间，每隔10s检查失效服务，并移除列表 (Spring Cloud默认该配置是 60s)
    eviction-interval-timer-in-ms: 5000