spring:
  application:
    name: neckpets
  profiles:
    active: local
    include: dev
  jpa:
    show-sql: true
  cache:
    type: redis
    redis:
      key-prefix: cache
      cache-null-values: true
  main:
    allow-bean-definition-overriding: true
  aop:
    auto: true
server:
  port: 8886
  tomcat:
    max-threads: 300
    min-spare-threads: 0
    max-connections: 200
    uri-encoding: UTF-8
management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  pattern:
    console: "%d - %msg%n"